name: DVC Repro

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: dvc-repro-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: '3.10'
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  repro:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ env.PYTHON_VERSION }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ env.PYTHON_VERSION }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install "dvc[s3]"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Initialize DVC and remote
        run: |
          dvc init -q || true
          dvc remote add -f -d s3remote ${{ secrets.DVC_REMOTE_URL }}
          dvc remote modify s3remote region ${{ env.AWS_REGION }}

      - name: Pull existing data/artifacts
        run: dvc pull || true

      - name: Reproduce pipeline
        run: dvc repro --no-commit

      - name: Push data/artifacts to S3
        run: dvc push

      - name: Upload metrics and samples
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dvc-outputs
          path: |
            metrics.json
            artifacts/samples/**

